In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as pd

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Educator_Salary.csv', low_memory=False)
df2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Educator_Mobility.csv', low_memory=False)

In [ ]:
display(df1.head())
display(df2.head())

,Unnamed: 0,School Year,District Code,District,School Code,Organization,Race,Gender,Grade,SpecialDemo,...,Staff Category,Job Classification,Experience,Educators (FTE),Average Total Salary,Average State Salary,Average Local Salary,Average Federal Salary,Average Years of Experience,Average Years of Age
0,0,2020,24,Smyrna School District,697,Smyrna Administrative Office,White,All Educators,All Educators,Regular,...,Official/Administrative,ALL,ALL,14,"95,625.22","54,023.65","41,601.56",NaN,19,53
1,1,2020,24,Smyrna School District,697,Smyrna Administrative Office,White,All Educators,All Educators,Regular,...,Pupil Support,ALL,ALL,1,"97,917.55","60,056.88","37,860.68",NaN,1,33
2,2,2020,24,Smyrna School District,697,Smyrna Administrative Office,White,All Educators,All Educators,All Educators,...,ALL,ALL,ALL,25,"48,982.63","35,892.53","13,090.1",NaN,20,46
3,3,2020,24,Smyrna School District,697,Smyrna Administrative Office,White,All Educators,All Educators,Regular,...,Instructional Support,"Supervisor, Instructional",ALL,3,"115,362.61","64,883.95","50,478.65",NaN,12,53
4,4,2020,24,Smyrna School District,697,Smyrna Administrative Office,White,All Educators,All Educators,All Educators,...,ALL,ALL,ALL,46,"69,886.27","44,649.62","25,236.64",NaN,19,48

,Unnamed: 0,School Year,District Code,District,School Code,Organization,Race,Gender,Grade,SpecialDemo,...,Retention Type,Same School Retention Rate,Transfer Rate Within District,Transfer Rate Between Districts,Turnover Rate,Same School Numerator,Transfer Within District Numerator,Transfer Between Districts Numerator,Turnover Numerator,Total Number of Staff
0,0,2023,0,State of Delaware,0,State of Delaware,African American,All Educators,All Educators,All Educators,...,Five Year Percentage,43.8,11.4,18.6,26.2,426,111,181,255,973
1,1,2023,0,State of Delaware,0,State of Delaware,African American,All Educators,All Educators,All Educators,...,Four Year Percentage,40.9,10.4,17.2,31.4,311,79,131,239,760
2,2,2023,0,State of Delaware,0,State of Delaware,African American,All Educators,All Educators,All Educators,...,One Year Percentage,79.5,3.8,8.5,8.3,931,44,100,97,"1,171"
3,3,2023,0,State of Delaware,0,State of Delaware,African American,All Educators,All Educators,All Educators,...,Three Year Percentage,58.6,9.0,14.7,17.7,656,101,165,198,"1,120"
4,4,2023,0,State of Delaware,0,State of Delaware,African American,All Educators,All Educators,All Educators,...,Two Year Percentage,66.4,7.2,11.9,14.4,773,84,139,168,"1,164"